name: Continuous Integration (CI)
# We define the event that will trigger this workflow.
# It will be executed with every 'push' to the 'main' branch.
on:
  push:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18','20']
    steps:
      - name: 1. Download Repository Code
        uses: actions/checkout@v4
      - name: 2. Configure Node.js Environment (${{matrix.node-version}})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 3. Install Project Dependencies
        run: npm ci
      - name: 4. Run Unit Tests with Jest
        run: npm test
  deploy:
      needs: [build_and_test]
      runs-on:
        ubuntu-latest
      steps:
      - name: 1. download the code
        uses: actions/checkout@v4
      - name: 2. despliegue
        run: echo "despliegue exitoso"
