name: Integraci칩n Continua (CI)
# Definimos el evento que disparar치 este workflow.
# Se ejecutar치 con cada 'push' a la rama 'main'.
on:
  push:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18','20']
    steps:
      - name: 1. Descargar C칩digo del Repositorio
        uses: actions/checkout@v4
      - name: 2. Configurar Entorno de Node.js (${{matrix.node-version}})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 3. Instalar Dependencias del Proyecto
        run: npm ci
      - name: 4. Ejecutar Pruebas Unitarias con Jest
        run: npm test
